apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agent
spec:
  securityContext:
    runAsUser: 0 
  containers:
  - name: node
    image: node:22-alpine
    command:
      - cat
    tty: true

  - name: docker
    image: docker:27-cli
    command:
      - cat
    tty: true
    volumeMounts:
    - name: docker-sock
      mountPath: /var/run/docker.sock

  - name: kubectl
    image: bitnami/kubectl
    command:
      - cat
    tty: true
    resources:
      requests:
        cpu: "100m"
        memory: "128Mi"

  volumes:
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock