apiVersion: v1
kind: Pod

metadata:
  labels:
    app: jenkins-agent

spec:
  containers:

  - name: node
    image: node:22-alpine
    command:
      - cat
    tty: true

  - name: docker
    image: docker:27-cli
    command:
      - cat
    tty: true

  - name: kubectl
    image: bitnami/kubectl
    command:
      - cat
    tty: true