apiVersion: v1
kind: Namespace
metadata:
  name: ns-wiriarte

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: config-wiriarte
  namespace: ns-wiriarte
data:
  AMBIENTE: "LABORATORIO"

---
apiVersion: v1
kind: Secret
metadata:
  name: secret-wiriarte
  namespace: ns-wiriarte
type: Opaque
stringData:
  API_KEY: "laboratorio-2026"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-wiriarte
  namespace: ns-wiriarte

spec:
  replicas: 2

  selector:
    matchLabels:
      app: app-wiriarte

  template:
    metadata:
      labels:
        app: app-wiriarte

    spec:
      containers:
        - name: app-wiriarte
          image: wiriarte/laboratorio-final:waldo-iriarte
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: AMBIENTE
              valueFrom:
                configMapKeyRef:
                  name: config-wiriarte
                  key: AMBIENTE
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: secret-wiriarte
                  key: API_KEY

---
apiVersion: v1
kind: Service
metadata:
  name: svc-wiriarte
  namespace: ns-wiriarte

spec:
  selector:
    app: app-wiriarte
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP