apiVersion: apps/v1
kind: Deployment

metadata:
  name: laboratorio-final
  namespace: ns-wiriarte

spec:
  replicas: 2

  selector:
    matchLabels:
      app: laboratorio-final

  template:
    metadata:
      labels:
        app: laboratorio-final

    spec:
      containers:
      - name: laboratorio-final
        image: wiriarte/laboratorio-final:wiriarte
        imagePullPolicy: Always
        ports:
          - containerPort: 3000
        env:
          - name: AMBIENTE
            value: "KUBERNETES"

          - name: API_KEY
            value: "laboratorio-k8s"